"""Built-in adapter for the public news sources shipped by Vibe-Research.

The original project did not depend on a Vibe API for its two stock-scoped
feeds.  It called the public Eastmoney announcement and search endpoints via
``stock_insight``.  This adapter reuses that already audited boundary and
normalizes the result into the watchlist-news contract.  A separately supplied
VibePublic configuration still takes precedence in the registry.
"""
from __future__ import annotations

import hashlib
import threading
from collections.abc import Callable
from datetime import UTC, datetime
from typing import Any
from zoneinfo import ZoneInfo

from app.data_providers.base import ProviderCapabilities
from app.data_providers.news_contract import NewsCategory, NewsFetchResult, NewsItem
from app.services import stock_insight

_SHANGHAI = ZoneInfo("Asia/Shanghai")
_DATA_VERSION = "vibe-research-eastmoney-v1"


def _as_datetime(value: Any) -> datetime | None:
    if value is None or str(value).strip() == "":
        return None
    if isinstance(value, datetime):
        result = value
    else:
        text = str(value).strip()
        try:
            result = datetime.fromisoformat(text.replace("Z", "+00:00"))
        except ValueError:
            try:
                result = datetime.strptime(text[:10], "%Y-%m-%d")
            except ValueError:
                return None
    if result.tzinfo is None:
        result = result.replace(tzinfo=_SHANGHAI)
    return result.astimezone(UTC)


def _code(symbol: str) -> str:
    return symbol.split(".", 1)[0]


def _stable_id(category: str, symbol: str, item: dict[str, Any]) -> str:
    basis = "|".join(
        (
            "vibe-research",
            category,
            symbol,
            str(item.get("title") or item.get("新闻标题") or ""),
            str(item.get("date") or item.get("发布时间") or ""),
            str(item.get("url") or item.get("新闻链接") or ""),
        )
    )
    return hashlib.sha256(basis.encode("utf-8")).hexdigest()[:32]


class VibeResearchProvider:
    """Use Vibe-Research's existing public stock-news source implementation."""

    name = "vibe_research"
    display_name = "Vibe-Research 公开源"
    capabilities = ProviderCapabilities(news=True)

    def __init__(self, *, clock: Callable[[], datetime] | None = None) -> None:
        self._clock = clock or (lambda: datetime.now(UTC))
        self._lock = threading.RLock()
        self._cache: dict[tuple[NewsCategory, str], tuple[datetime, list[NewsItem]]] = {}

    def close(self) -> None:
        return None

    def get_news(
        self,
        category: NewsCategory,
        symbols: list[str],
        start_time: datetime | None = None,
        end_time: datetime | None = None,
        query: str | None = None,
        limit: int = 30,
        cursor: str | None = None,
    ) -> NewsFetchResult:
        del cursor
        fetched_at = self._clock()
        if category == "today_highlight":
            raise ValueError("today_highlight is generated by the watchlist service")
        if not symbols:
            return NewsFetchResult(items=[], source_status="empty", fetched_at=fetched_at)
        if not 1 <= limit <= 100:
            raise ValueError("limit must be between 1 and 100")

        normalized = list(dict.fromkeys(str(symbol).strip().upper() for symbol in symbols if str(symbol).strip()))
        items: list[NewsItem] = []
        failures: list[str] = []
        successful = 0
        for symbol in normalized:
            try:
                rows, from_cache = self._get_symbol(category, symbol, limit=max(limit, 20))
                successful += 1
                items.extend(rows)
                if from_cache:
                    # Cached rows are still valid source data; no status change.
                    continue
            except Exception as exc:  # one symbol must not hide others
                failures.append(f"{symbol}: {exc}")

        filtered = self._filter(items, start_time, end_time, query, limit)
        if failures and filtered:
            status = "invalid"
            message = "; ".join(failures[:3])
        elif failures and not successful:
            status = "unavailable"
            message = "; ".join(failures[:3])
        elif failures:
            status = "invalid"
            message = "; ".join(failures[:3])
        elif not filtered:
            status = "empty"
            message = "; ".join(failures[:3]) if failures else None
        else:
            status = "ok"
            message = "; ".join(failures[:3]) if failures else None
        return NewsFetchResult(
            items=filtered,
            source_status=status,
            source_message=message,
            fetched_at=fetched_at,
        )

    def _get_symbol(self, category: NewsCategory, symbol: str, limit: int) -> tuple[list[NewsItem], bool]:
        now = self._clock()
        key = (category, symbol)
        with self._lock:
            hit = self._cache.get(key)
            if hit and (now - hit[0]).total_seconds() < 900:
                return list(hit[1]), True

        code = _code(symbol)
        if category == "announcement":
            raw_rows = stock_insight.announcements(code, limit=min(max(limit, 1), 50))
            rows = [self._announcement(symbol, row, now) for row in raw_rows]
        else:
            raw_rows = stock_insight.stock_news(code, limit=min(max(limit, 1), 50))
            rows = [self._news(symbol, row, now) for row in raw_rows]
        normalized = [item for item in rows if item is not None]
        with self._lock:
            self._cache[key] = (now, normalized)
        return normalized, False

    def _announcement(self, symbol: str, row: dict[str, Any], fetched_at: datetime) -> NewsItem | None:
        title = str(row.get("title") or "").strip()
        if not title:
            return None
        published = _as_datetime(row.get("date"))
        item_id = _stable_id("announcement", symbol, row)
        return NewsItem(
            id=item_id,
            category="announcement",
            symbol=symbol,
            title=title,
            summary=str(row.get("type") or "").strip() or None,
            url=str(row.get("url") or "").strip() or None,
            source="东方财富公告",
            published_at=published,
            fetched_at=fetched_at,
            data_version=_DATA_VERSION,
            source_ids=[item_id],
        )

    def _news(self, symbol: str, row: dict[str, Any], fetched_at: datetime) -> NewsItem | None:
        title = str(row.get("新闻标题") or "").strip()
        if not title:
            return None
        published = _as_datetime(row.get("发布时间"))
        source = str(row.get("文章来源") or "公开新闻").strip() or "公开新闻"
        item_id = _stable_id("public_news", symbol, row)
        return NewsItem(
            id=item_id,
            category="public_news",
            symbol=symbol,
            title=title,
            url=str(row.get("新闻链接") or "").strip() or None,
            source=source,
            published_at=published,
            fetched_at=fetched_at,
            data_version=_DATA_VERSION,
            source_ids=[item_id],
        )

    @staticmethod
    def _filter(
        items: list[NewsItem],
        start_time: datetime | None,
        end_time: datetime | None,
        query: str | None,
        limit: int,
    ) -> list[NewsItem]:
        def aware(value: datetime | None) -> datetime | None:
            if value is None:
                return None
            return value.replace(tzinfo=UTC) if value.tzinfo is None else value.astimezone(UTC)

        start = aware(start_time)
        end = aware(end_time)
        needle = (query or "").strip().casefold()
        output = []
        for item in items:
            timestamp = item.published_at or item.fetched_at
            if start and timestamp < start:
                continue
            if end and timestamp > end:
                continue
            if needle and needle not in f"{item.title} {item.summary or ''} {item.source}".casefold():
                continue
            output.append(item)
        output.sort(key=lambda value: value.published_at or value.fetched_at, reverse=True)
        return output[:limit]
