"""HTTP adapter for the operator-provided Vibe-Research news API."""
from __future__ import annotations

import copy
import hashlib
import logging
import os
import time
from collections.abc import Callable
from datetime import UTC, datetime
from typing import Any

import httpx

from app.config import settings
from app.data_providers.base import ProviderCapabilities
from app.data_providers.custom.mapper import extract_rows
from app.data_providers.news_contract import NewsCategory, NewsFetchResult, NewsItem
from app.data_providers.vibe_public_config import NewsEndpointConfig, VibePublicConfig

logger = logging.getLogger(__name__)


class NewsProviderError(RuntimeError):
    """A typed upstream error; callers must not silently fall back to another source."""

    def __init__(self, message: str, *, status: str = "unavailable") -> None:
        self.status = status
        super().__init__(f"{status}: {message}")


def _path_get(value: Any, path: str) -> Any:
    current = value
    for part in path.split(".") if path else []:
        if isinstance(current, dict):
            current = current.get(part)
        else:
            return None
    return current


def _path_set(target: dict[str, Any], path: str, value: Any) -> None:
    parts = [part for part in path.split(".") if part]
    if not parts:
        return
    current = target
    for part in parts[:-1]:
        child = current.get(part)
        if not isinstance(child, dict):
            child = {}
            current[part] = child
        current = child
    current[parts[-1]] = value


def _format_time(value: datetime | None, cfg: NewsEndpointConfig) -> str | None:
    if value is None:
        return None
    if cfg.date_format:
        return value.strftime(cfg.date_format)
    if cfg.date_only:
        return value.date().isoformat()
    return value.isoformat()


def _token_from_env(name: str | None) -> str | None:
    if not name:
        return None
    token = os.getenv(name)
    if token:
        return token[:4096]
    for path in (
        settings.data_dir / "private" / name,
        settings.data_dir / "secrets" / name,
        settings.data_dir / f".{name}",
    ):
        try:
            if path.is_file():
                value = path.read_text(encoding="utf-8").strip()
                if value:
                    return value[:4096]
        except OSError:
            continue
    return None


class VibePublicProvider:
    """Fetch and normalize public news in batches, without user state."""

    def __init__(
        self,
        config: VibePublicConfig,
        *,
        client: httpx.Client | None = None,
        clock: Callable[[], datetime] | None = None,
    ) -> None:
        self.config = config
        self.name = config.name
        self.capabilities = ProviderCapabilities(news=config.enabled and bool(config.datasets))
        self._client = client or httpx.Client(timeout=30.0, follow_redirects=True)
        self._owns_client = client is None
        self._clock = clock or (lambda: datetime.now(UTC))

    def close(self) -> None:
        if self._owns_client:
            self._client.close()

    def validate(self) -> list[str]:
        return self.config.validate()

    def get_news(
        self,
        category: NewsCategory,
        symbols: list[str],
        start_time: datetime | None = None,
        end_time: datetime | None = None,
        query: str | None = None,
        limit: int = 30,
        cursor: str | None = None,
    ) -> NewsFetchResult:
        fetched_at = self._clock()
        if category == "today_highlight":
            raise NewsProviderError("today_highlight is generated by the user service", status="invalid")
        endpoint = self.config.datasets.get(category)
        if endpoint is None or not self.config.enabled:
            raise NewsProviderError(f"dataset {category!r} is not configured", status="unavailable")
        if not symbols:
            return NewsFetchResult(items=[], source_status="empty", fetched_at=fetched_at)
        if not 1 <= limit <= 100:
            raise NewsProviderError("limit must be between 1 and 100", status="invalid")

        payload = self._request_payload(
            endpoint,
            category=category,
            symbols=symbols,
            start_time=start_time,
            end_time=end_time,
            query=query,
            limit=limit,
            cursor=cursor,
        )
        rows = extract_rows(payload, endpoint.response_path)
        if not rows:
            return NewsFetchResult(items=[], source_status="empty", fetched_at=fetched_at)

        items: list[NewsItem] = []
        invalid_rows = 0
        for row in rows:
            try:
                mapped = self._map_row(row, endpoint, category, symbols, fetched_at)
                items.append(NewsItem.model_validate(mapped))
            except (TypeError, ValueError) as exc:
                invalid_rows += 1
                logger.warning("VibePublic %s row rejected: %s", category, exc)

        if not items:
            raise NewsProviderError(
                f"{category} response contained no valid news rows ({invalid_rows} rejected)",
                status="invalid",
            )
        next_cursor = _path_get(payload, endpoint.next_cursor_path) if endpoint.next_cursor_path else None
        status = "invalid" if invalid_rows else "ok"
        message = f"{invalid_rows} invalid rows ignored" if invalid_rows else None
        return NewsFetchResult(
            items=items,
            source_status=status,
            source_message=message,
            next_cursor=str(next_cursor) if next_cursor else None,
            fetched_at=fetched_at,
        )

    def _request_payload(
        self,
        cfg: NewsEndpointConfig,
        *,
        category: str,
        symbols: list[str],
        start_time: datetime | None,
        end_time: datetime | None,
        query: str | None,
        limit: int,
        cursor: str | None,
    ) -> Any:
        params = dict(cfg.params)
        body = copy.deepcopy(cfg.body)
        symbol_value: list[str] | str = symbols if cfg.symbols_style == "list" else ",".join(symbols)
        values = {
            "symbols": symbol_value,
            "category": category,
            "start": _format_time(start_time, cfg),
            "end": _format_time(end_time, cfg),
            "query": query,
            "limit": limit,
            "cursor": cursor,
        }
        bindings = (
            ("symbols", cfg.symbols_param, cfg.symbols_body_path),
            ("category", cfg.category_param, cfg.category_body_path),
            ("start", cfg.start_param, cfg.start_body_path),
            ("end", cfg.end_param, cfg.end_body_path),
            ("query", cfg.query_param, cfg.query_body_path),
            ("limit", cfg.limit_param, cfg.limit_body_path),
            ("cursor", cfg.cursor_param, cfg.cursor_body_path),
        )
        for name, param_name, body_path in bindings:
            value = values[name]
            if value is None or (not param_name and not body_path):
                continue
            if body_path:
                _path_set(body, body_path, value)
            elif cfg.method == "GET":
                params[param_name] = value
            else:
                body[param_name] = value

        headers: dict[str, str] = {}
        token = _token_from_env(self.config.auth.token_env)
        auth = self.config.auth
        if token:
            if auth.type == "bearer":
                headers[auth.header] = f"Bearer {token}"
            elif auth.type == "header":
                headers[auth.header] = token
            elif auth.type == "query":
                params[auth.param] = token
            elif auth.type == "body":
                body[auth.param] = token

        method = cfg.method.upper()
        kwargs: dict[str, Any] = {"headers": headers, "timeout": cfg.timeout}
        if method == "GET":
            kwargs["params"] = params
        else:
            kwargs["json"] = body
            kwargs["params"] = params
        for attempt in range(2):
            try:
                response = self._client.request(method, cfg.url, **kwargs)
                response.raise_for_status()
                try:
                    return response.json()
                except ValueError as exc:
                    raise NewsProviderError("upstream response is not valid JSON", status="invalid") from exc
            except NewsProviderError:
                raise
            except (httpx.TimeoutException, httpx.TransportError) as exc:
                if attempt == 1:
                    raise NewsProviderError("upstream request failed", status="unavailable") from exc
                time.sleep(0.2)
            except httpx.HTTPStatusError as exc:
                raise NewsProviderError(
                    f"upstream returned HTTP {exc.response.status_code}",
                    status="unavailable",
                ) from exc
        raise NewsProviderError("upstream request failed", status="unavailable")

    def _map_row(
        self,
        row: dict[str, Any],
        cfg: NewsEndpointConfig,
        category: str,
        symbols: list[str],
        fetched_at: datetime,
    ) -> dict[str, Any]:
        mapped: dict[str, Any] = {}
        for external, canonical in cfg.field_map.items():
            mapped[canonical] = _path_get(row, external)
        title = str(mapped.get("title") or "").strip()
        if not title:
            raise ValueError("title is required")
        symbol = mapped.get("symbol")
        if not symbol and len(symbols) == 1:
            symbol = symbols[0]
        normalized_symbol = str(symbol).strip().upper() if symbol else None
        article_id = str(mapped.get("id") or "").strip()
        if not article_id:
            basis = "|".join(
                [self.name, category, normalized_symbol or "", str(mapped.get("published_at") or ""), title, str(mapped.get("url") or "")]
            )
            article_id = hashlib.sha256(basis.encode("utf-8")).hexdigest()[:32]
        mapped.update(
            {
                "id": article_id,
                "category": category,
                "symbol": normalized_symbol,
                "source": str(mapped.get("source") or self.config.display_name).strip(),
                "title": title,
                "fetched_at": fetched_at,
                "data_version": cfg.data_version,
                "generated": False,
                "source_ids": [article_id],
            }
        )
        return mapped
